# Generated by Django 3.2.18 on 2023-03-01 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('overalDuration', models.CharField(blank=True, max_length=100, null=True)),
                ('rdoc', models.DateField(auto_now_add=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('finishedDate', models.DateField()),
                ('isCompleted', models.BooleanField(default=False)),
                ('isPrinted', models.BooleanField(default=False)),
                ('priority', models.CharField(blank=True, max_length=10, null=True)),
                ('jobType', models.CharField(blank=True, max_length=100, null=True)),
                ('tradesNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('unit', models.IntegerField()),
                ('isTradesConfirmed', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_maintenanceschedule', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_maintenanceSchedule', to='inventory.inventory')),
                ('spareTool', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='SpareTool_MaintenanceSchedule', to='asset.sparetool')),
                ('tradesList', models.ManyToManyField(related_name='userList_maintenanceSchedule', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_maintenanceschedul', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt', '-updatedAt'],
            },
        ),
    ]
