# Generated by Django 3.2.18 on 2023-03-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('asset', '0001_initial'),
        ('workOrder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_maintenanceSchedule', to='asset.asset'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_maintenanceSchedule', to='inventory.inventory'),
        ),
    ]
