# Generated by Django 3.2.18 on 2023-03-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0002_auto_20230301_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='OrderNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
