# Generated by Django 3.2.18 on 2023-03-01 10:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stationName', models.CharField(blank=True, max_length=100, null=True)),
                ('stationNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('regionName', models.CharField(blank=True, max_length=100, null=True)),
                ('yearBuilt', models.DateField()),
                ('isStandard', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_stations', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_station', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt', '-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='SpareTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('spareSerialNo', models.CharField(blank=True, max_length=100, null=True)),
                ('spareName', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_spareTools', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_spareTool', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt', '-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('officeName', models.CharField(blank=True, max_length=100, null=True)),
                ('OfficeNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('yearBuilt', models.DateField()),
                ('isStandard', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_office', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='station_office', to='asset.station')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_offce', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt', '-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='CategoryTwo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_categoryTwo', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_categryTwo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt', '-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('serialNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('assetName', models.CharField(blank=True, max_length=100, null=True)),
                ('costSpent', models.CharField(blank=True, max_length=100, null=True)),
                ('totalPrice', models.CharField(blank=True, max_length=100, null=True)),
                ('lifeSpan', models.CharField(blank=True, max_length=100, null=True)),
                ('mtl', models.CharField(blank=True, max_length=100, null=True)),
                ('siteName', models.CharField(blank=True, max_length=100, null=True)),
                ('userManual', models.FileField(blank=True, null=True, upload_to='userManual/asset/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'ppt'])])),
                ('orderStatus', models.BooleanField(default=False)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('iam', models.BooleanField(default=False)),
                ('maintenanceNumber', models.IntegerField(default=0)),
                ('unit', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('categoryOne', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CategoryTwo_assets', to='asset.categorytwo')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_assets', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='office_asset', to='asset.office')),
                ('spareTool', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='SpareTool_asset', to='asset.sparetool')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_asset', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt', '-updatedAt'],
            },
        ),
    ]
