# Generated by Django 3.2.18 on 2023-03-04 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uaa', '0005_profile_department'),
        ('asset', '0002_auto_20230301_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_asset', to='uaa.department'),
        ),
        migrations.AddField(
            model_name='categorytwo',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_categoryTwo', to='uaa.department'),
        ),
        migrations.AddField(
            model_name='office',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_office', to='uaa.department'),
        ),
        migrations.AddField(
            model_name='sparetool',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_spareTool', to='uaa.department'),
        ),
        migrations.AddField(
            model_name='station',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_station', to='uaa.department'),
        ),
    ]
