# Generated by Django 3.2.18 on 2023-03-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20230303_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytwo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='office',
            name='isStandard',
        ),
        migrations.RemoveField(
            model_name='station',
            name='yearBuilt',
        ),
    ]
