# Generated by Django 3.2.18 on 2023-03-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenanceReport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='mrNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
