# Generated by Django 3.2.18 on 2023-03-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0003_maintenanceschedule_ordernumber'),
        ('maintenanceReport', '0002_maintenancereport_mrnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancereport',
            name='MaintenanceSchedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maintenanceSchedule_maitenaceR', to='workOrder.maintenanceschedule'),
        ),
    ]
