# Generated by Django 3.2.18 on 2023-03-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenanceReport', '0004_alter_maintenancereport_maintenanceschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancereport',
            name='other',
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
