# Generated by Django 3.2.18 on 2023-03-01 10:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_categoryOne', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_categryOne', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt', '-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='TradesSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('maxTradeNumber', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_tradesSetting', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_tradesSettings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt', '-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('serialNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('spareName', models.CharField(blank=True, max_length=100, null=True)),
                ('costSpent', models.CharField(blank=True, max_length=100, null=True)),
                ('totalPrice', models.CharField(blank=True, max_length=100, null=True)),
                ('lifeSpan', models.CharField(blank=True, max_length=100, null=True)),
                ('mtl', models.CharField(blank=True, max_length=100, null=True)),
                ('siteName', models.CharField(blank=True, max_length=100, null=True)),
                ('userManual', models.FileField(blank=True, null=True, upload_to='userManual/inventory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'ppt'])])),
                ('orderStatus', models.BooleanField(default=False)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('iam', models.BooleanField(default=False)),
                ('maintenanceNumber', models.IntegerField(default=0)),
                ('unit', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('categoryOne', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CategoryOne_inventory', to='inventory.categoryone')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_inventory', to=settings.AUTH_USER_MODEL)),
                ('spareTool', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='SpareTool_inventry', to='asset.sparetool')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_inventry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt', '-updatedAt'],
            },
        ),
    ]
