# Generated by Django 3.2.18 on 2023-03-07 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uaa', '0005_profile_department'),
        ('inventory', '0002_auto_20230303_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryone',
            name='description',
        ),
        migrations.AddField(
            model_name='categoryone',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_categoryOno', to='uaa.department'),
        ),
    ]
