# Generated by Django 3.2.18 on 2023-03-07 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_auto_20230306_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradessetting',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_tradesSetting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tradessetting',
            name='updatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_tradesSettings', to=settings.AUTH_USER_MODEL),
        ),
    ]
