# Generated by Django 3.2.18 on 2023-03-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20230307_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='costSpent',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='userManual',
        ),
        migrations.AddField(
            model_name='inventory',
            name='lastMaintained',
            field=models.DateField(blank=True, null=True),
        ),
    ]
