# Generated by Django 3.2.18 on 2023-03-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20230313_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='iam',
            field=models.BooleanField(default=True),
        ),
    ]
