# Generated by Django 3.2.18 on 2023-03-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uaa', '0006_user_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileImage',
        ),
    ]
